### ISSUE TITLE
dict comprehension doesn't work in python 2.6

### ISSUE THREAD

**Issue by mgrauer** [girder/monkeybrains#18]
In the set_metadata.py utility, [this line](https://github.com/girder/monkeybrains/blob/9c91549b6eb6f4f3fc15961aa4981342e8184b63/utils/set_metadata.py#L126) causes an error in python 2.6

```
metadataToUpdate = {key: None for key in meta}
```

This line is removing any metadata keys that exist in the current metadata, by passing up a dictionary mapping each key to the value `None`.  It can be changed to be python 2.6 compliant like so

```
for key, value in meta.items():
    metadataToUpdate[key] = None
```

**Comment by mgrauer** [comment]
ping @Jeffrey-Young

**Comment by Jeffrey-Young** [comment]
@mgrauer 

I executed the updated script and ran into the following error. I'm not sure if this is a result of my changes, or some other issue.

  File "set_metadata.py", line 146, in <module>
    walkGirderTree(parent_id, 'folder')
  File "set_metadata.py", line 138, in walkGirderTree
    walkGirderTree(folder['_id'], 'folder', name)
  File "set_metadata.py", line 138, in walkGirderTree
    walkGirderTree(folder['_id'], 'folder', name)
  File "set_metadata.py", line 76, in walkGirderTree
    'parentId': ancestorFolderId
  File "/usr/lib/python2.6/site-packages/girder_client/__init__.py", line 231, in get
    return self.sendRestRequest('GET', path, parameters)
  File "/usr/lib/python2.6/site-packages/girder_client/**init**.py", line 218, in sendRestRequest
    'Girder-Token': self.token
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))

**Comment by mgrauer** [comment]
No, this is just a connection timeout, something we had seen before--it is the result of some network trouble between you and the server.

Since you only need to update two specific cases, you can create a copy of those two cases on your filesystem in some other location (or better yet, create a folder with a symlink to those two, to avoid copying), then point your script at the new location.  So the new location would look something like

```
/temporary_data
    /015
    /024
```

though I'm probably getting these path names not exactly right.

Since there will be many fewer network operations, you are less likely to run into a connection timeout.

**Comment by Jeffrey-Young** [comment]
I'm confused, in looking at the set_metadata.py script it appears as if it traverses the entire Girder file structure and isn't tied to any data locally except the metadata.json. I tried running the script on a revised copy of the metadata.json that only contained those two subjects and got a KeyError for subject 001 (which makes sense because this copy of the metadata has no info for 001).
